Support Test and CI
gtt-project/redmine_custom_fields_groups pull request #26
Opened 2024-05-07 01:34 UTC by sanak

Supports #24.

Changes proposed in this pull request:
- Add Test
- Add CI

@gtt-project/maintainer

2024-05-10 06:47 UTC, mopinfish requested changes
一点コメントしたのでご確認ください。

2024-05-10 06:47 UTC, mopinfish commented on test/functional/custom_fields_groups_controller_test.rb
> +    @request.session[:user_id] = 1 # admin
Railsのminitestにおいて、@request.sessionに値を設定する場合は、teardownメソッドで@request.session.clear を呼び出して、セッションをクリアすることが推奨されているようです。

```
  teardown do
    @request.session.clear
  end
```

これにより、各テストケースが独立して実行され、セッションの状態が他のテストに影響を与えることがなくなります。

2024-05-10 08:46 UTC, sanak commented on test/functional/custom_fields_groups_controller_test.rb
> +    @request.session[:user_id] = 1 # admin
@mopinfish 上記、了解です。
GitHub内で `@request.session.clear redmine` で検索してみたところ、事例としては見られませんでしたが、
https://github.com/search?q=%40request.session.clear+redmine&type=code

ご指摘通りのように思われましたので、以下のコミットで対応しました。
* コミット差分: https://github.com/gtt-project/redmine_custom_fields_groups/pull/26/commits/318ca271dddd80171d8c56738268137865ab7bef

2024-05-10 08:51 UTC, sanak commented
@mopinfish 別件で、ローカルmacOS環境でのテストで、システムテストがランダムに失敗することを確認しましたので、少し調整するようにします。
```sh
% bundle exec rake redmine:plugins:test NAME=redmine_custom_fields_groups RAILS_ENV=test
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from /Users/sanak/Projects/gtt-project/git/redmine-custom-fields-groups/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/postgresql_adapter.rb:883:in `new'
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from /Users/sanak/Projects/gtt-project/git/redmine-custom-fields-groups/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/postgresql_adapter.rb:883:in `new'
Run options: --seed 50837

# Running:

..................Capybara starting Puma...
* Version 6.4.2, codename: The Eagle of Durango
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:55498
[Screenshot Image]: /Users/sanak/Projects/gtt-project/git/redmine-custom-fields-groups/tmp/screenshots/failures_test_click_group_label_should_collapse-expand_fieldset_with_default_state_all_expended.png
F

Failure:
FieldsetTest#test_click_group_label_should_collapse/expand_fieldset_with_default_state_all_expended [plugins/redmine_custom_fields_groups/test/system/fieldset_test.rb:53]:
Expected false to be truthy.


rails test plugins/redmine_custom_fields_groups/test/system/fieldset_test.rb:16

......

Finished in 9.333095s, 2.6786 runs/s, 23.5720 assertions/s.
25 runs, 220 assertions, 1 failures, 0 errors, 0 skips
```

2024-05-10 13:02 UTC, sanak commented
@mopinfish 上記のシステムテストがランダムに失敗する問題については、Issueの編集モード切り替え後の初回の操作で発生するようでしたので、編集(`Edit`)リンクのクリック後に編集画面の展開とコメント欄へのフォーカス設定が完了するまで待った上で、さらにスリープ(0.1秒)を追加することで対応しました。(コミット差分: https://github.com/gtt-project/redmine_custom_fields_groups/pull/26/commits/5f2b99f69304450c3727298edff735155787004e)
```diff
      # issue edit
      page.first(:link, 'Edit').click
+     page.find('#issue_notes:focus')
+     sleep 0.1
```
Redmine本体側のIssueの編集(`Edit`)リンククリック時処理:
* https://github.com/redmine/redmine/blob/5.1-stable/app/views/issues/_action_menu.html.erb#L2-L3
  ```erb
  <%= link_to l(:button_edit), edit_issue_path(@issue),
              :onclick => 'showAndScrollTo("update", "issue_notes"); return false;',
  ```
* https://github.com/redmine/redmine/blob/5.1-stable/public/javascripts/application.js#L22-L28
  ```js
  function showAndScrollTo(id, focus) {
    $('#'+id).show();
    if (focus !== null) {
      $('#'+focus).focus();
    }
    $('html, body').animate({scrollTop: $('#'+id).offset().top}, 100);
  }
  ```

---

合わせて、システムテストのテスト名とコメント箇所を少し変更しました(コミット差分:https://github.com/gtt-project/redmine_custom_fields_groups/pull/26/commits/8bc320d726cd22293adcb616044e746e18bb47db) 。
(フィールドセットのラベル箇所の名称を、 [ビュー](https://github.com/gtt-project/redmine_custom_fields_groups/blob/main/app/views/issues/_form_custom_fields.html.erb#L41) での変数名(`title`)に合わせています。)

お手数ですが、お手すきの際に再度確認頂けると助かります。🙇

2024-05-17 06:35 UTC, mopinfish approved these changes
Approveしました。

2024-05-17 08:50 UTC, sanak commented
@mopinfish 確認頂き、ありがとうございます！
一旦マージ後、README.mdの更新(#18)の方を進めていくようにします。🙇

2024-05-17 08:51 UTC, merged